# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMVVMTodo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxMVVMTodo
pod 'Alamofire', '~> 5.2'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SDWebImage' 
end
